name: face-detector
version: 0.1.0
summary: OpenCV Face Detector
description: ROSified version of a simple OpenCV face detector

apps:
  face-detector:
    command: roslaunch.wrapper face_detector face_detector.launch
    daemon: simple
    caps:
      - network-listener

parts:
  foo:
    plugin: catkin
    source: .
    catkin-packages:
      - face_detector
    stage-packages:
      - ros-indigo-ros-core
      - ros-indigo-usb-cam
  wrappers:
    plugin: copy
    files:
      roslaunch.wrapper: roslaunch.wrapper
